apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactquiz-docker-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactquiz-docker
  template:
    metadata:
      labels:
        app: reactquiz-docker
    spec:
      containers:
      - name: reactquiz-docker
        image: saisamarth21/reactquiz-docker
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "200m"
