apiVersion: v1
kind: Service
metadata:
  name: reactquiz-docker-srv
spec:
  type: NodePort
  selector:
    app: reactquiz-docker
  ports:
  - name: reactquiz-docker
    port: 3000
    targetPort: 3000
